export const provinces = [
  { id: 0, name: "San José" },
  { id: 1, name: "Alajuela" },
  { id: 2, name: "Cartago" },
  { id: 3, name: "Heredia" },
  { id: 4, name: "Guanacaste" },
  { id: 5, name: "Puntarenas" },
  { id: 6, name: "Limón" },
];

const cantons = [
  { id: 0, name: "San José", idProvince: 0 },
  { id: 1, name: "Acosta", idProvince: 0 },
  { id: 2, name: "Alajuelita", idProvince: 0 },
  { id: 3, name: "Aserrí", idProvince: 0 },
  { id: 4, name: "Curridabat", idProvince: 0 },
  { id: 5, name: "Desamparados", idProvince: 0 },
  { id: 6, name: "Dota", idProvince: 0 },
  { id: 7, name: "Escazú", idProvince: 0 },
  { id: 8, name: "Goicoechea", idProvince: 0 },
  { id: 9, name: "León Cortés", idProvince: 0 },
  { id: 10, name: "Montes de Oca", idProvince: 0 },
  { id: 11, name: "Mora", idProvince: 0 },
  { id: 12, name: "Moravia", idProvince: 0 },
  { id: 13, name: "Pérez Zeledón", idProvince: 0 },
  { id: 14, name: "Puriscal", idProvince: 0 },
  { id: 15, name: "Santa Ana", idProvince: 0 },
  { id: 16, name: "Tarrazú", idProvince: 0 },
  { id: 17, name: "Tibás", idProvince: 0 },
  { id: 18, name: "Turrubares", idProvince: 0 },
  { id: 19, name: "Vázques de Coronado", idProvince: 0 },
  { id: 20, name: "Cartago", idProvince: 2 },
  { id: 21, name: "Paraíso", idProvince: 2 },
  { id: 22, name: "La Unión", idProvince: 2 },
  { id: 23, name: "Jimenéz", idProvince: 2 },
  { id: 24, name: "Turrialba", idProvince: 2 },
  { id: 25, name: "Alvarado", idProvince: 2 },
  { id: 26, name: "Oreamuno", idProvince: 2 },
  { id: 27, name: "El Guarco", idProvince: 2 },
  { id: 28, name: "Puntarenas", idProvince: 5 },
  { id: 29, name: "Esparza", idProvince: 5 },
  { id: 30, name: "Buenos Aires", idProvince: 5 },
  { id: 31, name: "Montes de Oro", idProvince: 5 },
  { id: 32, name: "Osa", idProvince: 5 },
  { id: 33, name: "Quepos", idProvince: 5 },
  { id: 34, name: "Golfito", idProvince: 5 },
  { id: 35, name: "Coto Brus", idProvince: 5 },
  { id: 36, name: "Parrita", idProvince: 5 },
  { id: 37, name: "Corredores", idProvince: 5 },
  { id: 38, name: "Garabito", idProvince: 5 },
  { id: 39, name: "Monteverde", idProvince: 5 },
  { id: 40, name: "Puerto Jiménez", idProvince: 5 },
  { id: 41, name: "Alajuela", idProvince: 1 },
  { id: 42, name: "San Ramón", idProvince: 1 },
  { id: 43, name: "Grecia", idProvince: 1 },
  { id: 44, name: "San Mateo", idProvince: 1 },
  { id: 45, name: "Atenas", idProvince: 1 },
  { id: 46, name: "Naranjo", idProvince: 1 },
  { id: 47, name: "Palmares", idProvince: 1 },
  { id: 48, name: "Poás", idProvince: 1 },
  { id: 49, name: "Orotina", idProvince: 1 },
  { id: 50, name: "San Carlos", idProvince: 1 },
  { id: 51, name: "Zarcero", idProvince: 1 },
  { id: 52, name: "Sarchí", idProvince: 1 },
  { id: 53, name: "Upala", idProvince: 1 },
  { id: 54, name: "Los Chiles", idProvince: 1 },
  { id: 55, name: "Guatuso", idProvince: 1 },
  { id: 56, name: "Río Cuarto", idProvince: 1 },
  { id: 57, name: "Heredia", idProvince: 3 },
  { id: 58, name: "Barva", idProvince: 3 },
  { id: 59, name: "Belén", idProvince: 3 },
  { id: 60, name: "Flores", idProvince: 3 },
  { id: 61, name: "San Isidro", idProvince: 3 },
  { id: 62, name: "San Pablo", idProvince: 3 },
  { id: 63, name: "San Rafael", idProvince: 3 },
  { id: 64, name: "Santa Bárbara", idProvince: 3 },
  { id: 65, name: "Santo Domingo", idProvince: 3 },
  { id: 66, name: "Sarapiquí", idProvince: 3 },
  { id: 67, name: "Liberia", idProvince: 4 },
  { id: 68, name: "Nicoya", idProvince: 4 },
  { id: 69, name: "Santa Cruz", idProvince: 4 },
  { id: 70, name: "Bagaces", idProvince: 4 },
  { id: 71, name: "Carrillo", idProvince: 4 },
  { id: 72, name: "Cañas", idProvince: 4 },
  { id: 73, name: "Albangares", idProvince: 4 },
  { id: 74, name: "Tilarán", idProvince: 4 },
  { id: 75, name: "Nandayure", idProvince: 4 },
  { id: 76, name: "La Cruz", idProvince: 4 },
  { id: 77, name: "Hojancha", idProvince: 4 },
  { id: 78, name: "Limón", idProvince: 6 },
  { id: 79, name: "Pococí", idProvince: 6 },
  { id: 80, name: "Siquirres", idProvince: 6 },
  { id: 81, name: "Talamanca", idProvince: 6 },
  { id: 82, name: "Matina", idProvince: 6 },
  { id: 83, name: "Guácimo", idProvince: 6 },
];

const districts = [
  { id: 0, name: "Carmen", idCanton: 0 },
  { id: 1, name: "Catedral", idCanton: 0 },
  { id: 2, name: "Hatillo", idCanton: 0 },
  { id: 3, name: "Hospital", idCanton: 0 },
  { id: 4, name: "La Uruca", idCanton: 0 },
  { id: 5, name: "Mata Redonda", idCanton: 0 },
  { id: 6, name: "Merced", idCanton: 0 },
  { id: 7, name: "Pavas", idCanton: 0 },
  { id: 8, name: "San Francisco de dos Ríos", idCanton: 0 },
  { id: 9, name: "San Sebastián", idCanton: 0 },
  { id: 10, name: "Zapote", idCanton: 0 },
  { id: 11, name: "Cangrejal", idCanton: 1 },
  { id: 12, name: "Guaitil", idCanton: 1 },
  { id: 13, name: "Palmichal", idCanton: 1 },
  { id: 14, name: "Sabanillas", idCanton: 1 },
  { id: 15, name: "San Ignacio", idCanton: 1 },
  { id: 16, name: "Alajuelita", idCanton: 2 },
  { id: 17, name: "Concepción", idCanton: 2 },
  { id: 18, name: "San Antonio", idCanton: 2 },
  { id: 19, name: "San Felipe", idCanton: 2 },
  { id: 20, name: "San Josecito", idCanton: 2 },
  { id: 21, name: "Aserrí", idCanton: 3 },
  { id: 22, name: "Legua", idCanton: 3 },
  { id: 23, name: "Monterrey", idCanton: 3 },
  { id: 24, name: "Salitrillos", idCanton: 3 },
  { id: 25, name: "San Gabriel", idCanton: 3 },
  { id: 26, name: "Tarbaca", idCanton: 3 },
  { id: 27, name: "Vuelta de Jorco", idCanton: 3 },
  { id: 28, name: "Curridabat", idCanton: 4 },
  { id: 29, name: "Granadilla", idCanton: 4 },
  { id: 30, name: "Sánchez", idCanton: 4 },
  { id: 31, name: "Tirrases", idCanton: 4 },
  { id: 32, name: "Damas", idCanton: 5 },
  { id: 33, name: "Desamparados", idCanton: 5 },
  { id: 34, name: "Frailes", idCanton: 5 },
  { id: 35, name: "Gravilias", idCanton: 5 },
  { id: 36, name: "Los Guido", idCanton: 5 },
  { id: 37, name: "Patarrá", idCanton: 5 },
  { id: 38, name: "Rosario", idCanton: 5 },
  { id: 39, name: "San Antonio", idCanton: 5 },
  { id: 40, name: "San Cristóbal", idCanton: 5 },
  { id: 41, name: "San Juan de Dios", idCanton: 5 },
  { id: 42, name: "San Miguel", idCanton: 5 },
  { id: 43, name: "San Rafael Abajo", idCanton: 5 },
  { id: 44, name: "San Rafael Arriba", idCanton: 5 },
  { id: 45, name: "Copey", idCanton: 6 },
  { id: 46, name: "Jardín", idCanton: 6 },
  { id: 47, name: "Santa María", idCanton: 6 },
  { id: 48, name: "Escazú", idCanton: 7 },
  { id: 49, name: "San Antonio", idCanton: 7 },
  { id: 50, name: "San Rafael", idCanton: 7 },
  { id: 51, name: "Calle Blancos", idCanton: 8 },
  { id: 52, name: "Guadalupe", idCanton: 8 },
  { id: 53, name: "Ipís", idCanton: 8 },
  { id: 54, name: "Mata de Plátano", idCanton: 8 },
  { id: 55, name: "Purral", idCanton: 8 },
  { id: 56, name: "Rancho Redondo", idCanton: 8 },
  { id: 57, name: "San Francisco", idCanton: 8 },
  { id: 58, name: "San Pablo", idCanton: 9 },
  { id: 59, name: "San Andrés", idCanton: 9 },
  { id: 60, name: "Llano Bonito", idCanton: 9 },
  { id: 61, name: "San Isidro", idCanton: 9 },
  { id: 62, name: "Santa Cruz", idCanton: 9 },
  { id: 63, name: "San Antonio", idCanton: 9 },
  { id: 64, name: "Mercedes", idCanton: 10 },
  { id: 65, name: "Sabanilla", idCanton: 10 },
  { id: 66, name: "San Pedro", idCanton: 10 },
  { id: 67, name: "San Rafael", idCanton: 10 },
  { id: 68, name: "Cuidad Colón", idCanton: 11 },
  { id: 69, name: "Guayabo", idCanton: 11 },
  { id: 70, name: "Jaris", idCanton: 11 },
  { id: 71, name: "Picagres", idCanton: 11 },
  { id: 72, name: "Piedras Negras", idCanton: 11 },
  { id: 73, name: "Tabarcia", idCanton: 11 },
  { id: 74, name: "San Jerónimo", idCanton: 12 },
  { id: 75, name: "San Vicente", idCanton: 12 },
  { id: 76, name: "Trinidad", idCanton: 12 },
  { id: 77, name: "San Isidro de El General", idCanton: 13 },
  { id: 78, name: "Barú", idCanton: 13 },
  { id: 79, name: "Cajón", idCanton: 13 },
  { id: 80, name: "Daniel Flores", idCanton: 13 },
  { id: 81, name: "El General", idCanton: 13 },
  { id: 82, name: "La Amistad", idCanton: 13 },
  { id: 83, name: "Páramo", idCanton: 13 },
  { id: 84, name: "Pejibaye", idCanton: 13 },
  { id: 85, name: "Platanares", idCanton: 13 },
  { id: 86, name: "Río Nuevo", idCanton: 13 },
  { id: 87, name: "Rivas", idCanton: 13 },
  { id: 88, name: "San Pedro", idCanton: 13 },
  { id: 89, name: "Barbacoas", idCanton: 14 },
  { id: 90, name: "Candelarita", idCanton: 14 },
  { id: 91, name: "Chires", idCanton: 14 },
  { id: 92, name: "Desamparaditos", idCanton: 14 },
  { id: 93, name: "Grifo Alto", idCanton: 14 },
  { id: 94, name: "Mercedes Sur", idCanton: 14 },
  { id: 95, name: "San Antonio", idCanton: 14 },
  { id: 96, name: "San Rafael", idCanton: 14 },
  { id: 97, name: "Santiago", idCanton: 14 },
  { id: 98, name: "Brasil", idCanton: 15 },
  { id: 99, name: "Piedades", idCanton: 15 },
  { id: 100, name: "Pozos", idCanton: 15 },
  { id: 101, name: "Salitral", idCanton: 15 },
  { id: 102, name: "Santa Ana", idCanton: 15 },
  { id: 103, name: "Uruca", idCanton: 15 },
  { id: 104, name: "San Carlos", idCanton: 16 },
  { id: 105, name: "San Lorenzo", idCanton: 16 },
  { id: 106, name: "San Marcos", idCanton: 16 },
  { id: 107, name: "Anselmo Llorente", idCanton: 17 },
  { id: 108, name: "Cinco Esquinas", idCanton: 17 },
  { id: 109, name: "Colima", idCanton: 17 },
  { id: 110, name: "León XIII", idCanton: 17 },
  { id: 111, name: "San Juan", idCanton: 17 },
  { id: 112, name: "Carara", idCanton: 18 },
  { id: 113, name: "San Juan de Mata", idCanton: 18 },
  { id: 114, name: "San Luis", idCanton: 18 },
  { id: 115, name: "San Pablo", idCanton: 18 },
  { id: 116, name: "San Pedro", idCanton: 18 },
  { id: 117, name: "Cascajal", idCanton: 19 },
  { id: 118, name: "Dulce Nombre de Jesús", idCanton: 19 },
  { id: 119, name: "Patalillo", idCanton: 19 },
  { id: 120, name: "San Isidro", idCanton: 19 },
  { id: 121, name: "San Rafael", idCanton: 19 },
  { id: 122, name: "Oriental", idCanton: 20 },
  { id: 123, name: "Occidental", idCanton: 20 },
  { id: 124, name: "Carmen", idCanton: 20 },
  { id: 125, name: "San Nicolás", idCanton: 20 },
  { id: 126, name: "Aguacaliente", idCanton: 20 },
  { id: 127, name: "Guadalupe", idCanton: 20 },
  { id: 128, name: "Corralillo", idCanton: 20 },
  { id: 129, name: "Tierra Blanca", idCanton: 20 },
  { id: 130, name: "Dulce Nombre", idCanton: 20 },
  { id: 131, name: "Llano Grande", idCanton: 20 },
  { id: 132, name: "Quebradilla", idCanton: 20 },
  { id: 133, name: "Paraíso", idCanton: 21 },
  { id: 134, name: "Santiago", idCanton: 21 },
  { id: 135, name: "Orosi", idCanton: 21 },
  { id: 136, name: "Cachí", idCanton: 21 },
  { id: 137, name: "Llanos de Santa Lucía", idCanton: 21 },
  { id: 138, name: "Birrisito", idCanton: 21 },
  { id: 139, name: "Tres Ríos", idCanton: 22 },
  { id: 140, name: "San Diego", idCanton: 22 },
  { id: 141, name: "San Juan", idCanton: 22 },
  { id: 142, name: "San Rafael", idCanton: 22 },
  { id: 143, name: "Concepción", idCanton: 22 },
  { id: 144, name: "Dulce Nombre", idCanton: 22 },
  { id: 145, name: "San Ramón", idCanton: 22 },
  { id: 146, name: "Río Azul", idCanton: 22 },
  { id: 147, name: "Juan Viñas", idCanton: 23 },
  { id: 148, name: "Tucurrique", idCanton: 23 },
  { id: 149, name: "Pejibaye", idCanton: 23 },
  { id: 150, name: "La Victoria", idCanton: 23 },
  { id: 151, name: "Turrialba", idCanton: 24 },
  { id: 152, name: "La Suiza", idCanton: 24 },
  { id: 153, name: "Peralta", idCanton: 24 },
  { id: 154, name: "Santa Cruz", idCanton: 24 },
  { id: 155, name: "Santa Teresita", idCanton: 24 },
  { id: 156, name: "Pavones", idCanton: 24 },
  { id: 157, name: "Tuis", idCanton: 24 },
  { id: 158, name: "Tayutic", idCanton: 24 },
  { id: 159, name: "Santa Rosa", idCanton: 24 },
  { id: 160, name: "Tres Equis", idCanton: 24 },
  { id: 161, name: "La Isabel", idCanton: 24 },
  { id: 162, name: "Chirripó", idCanton: 24 },
  { id: 163, name: "Pacayas", idCanton: 25 },
  { id: 164, name: "Cervantes", idCanton: 25 },
  { id: 165, name: "Capellades", idCanton: 25 },
  { id: 166, name: "San Rafael", idCanton: 26 },
  { id: 167, name: "Cot", idCanton: 26 },
  { id: 168, name: "Potrero Cerrado", idCanton: 26 },
  { id: 169, name: "Cipreses", idCanton: 26 },
  { id: 170, name: "Santa Rosa", idCanton: 26 },
  { id: 171, name: "El Tejar", idCanton: 27 },
  { id: 172, name: "San Isidro", idCanton: 27 },
  { id: 173, name: "Tobosi", idCanton: 27 },
  { id: 174, name: "Patio de Agua", idCanton: 27 },
  { id: 175, name: "Puntarenas", idCanton: 28 },
  { id: 176, name: "Pitahaya", idCanton: 28 },
  { id: 177, name: "Chomes", idCanton: 28 },
  { id: 178, name: "Lepanto", idCanton: 28 },
  { id: 179, name: "Paquera", idCanton: 28 },
  { id: 180, name: "Manzanillo", idCanton: 28 },
  { id: 181, name: "Guacimal", idCanton: 28 },
  { id: 182, name: "Barranca", idCanton: 28 },
  { id: 183, name: "Isla del Coco", idCanton: 28 },
  { id: 184, name: "Cóbano", idCanton: 28 },
  { id: 185, name: "Chacarita", idCanton: 28 },
  { id: 186, name: "Chira", idCanton: 28 },
  { id: 187, name: "Acapulco", idCanton: 28 },
  { id: 188, name: "El Roble", idCanton: 28 },
  { id: 189, name: "Arancibia", idCanton: 28 },
  { id: 190, name: "Espíritu Santo", idCanton: 29 },
  { id: 191, name: "San Juan Grande", idCanton: 29 },
  { id: 192, name: "Maracona", idCanton: 29 },
  { id: 193, name: "San Rafael", idCanton: 29 },
  { id: 194, name: "San Jerónimo", idCanton: 29 },
  { id: 195, name: "Caldera", idCanton: 29 },
  { id: 196, name: "Buenos Aires", idCanton: 30 },
  { id: 197, name: "Volcán", idCanton: 30 },
  { id: 198, name: "Potrero Grande", idCanton: 30 },
  { id: 199, name: "Boruca", idCanton: 30 },
  { id: 200, name: "Pilas", idCanton: 30 },
  { id: 201, name: "Colinas", idCanton: 30 },
  { id: 202, name: "Chánguena", idCanton: 30 },
  { id: 203, name: "Biolley", idCanton: 30 },
  { id: 204, name: "Brunca", idCanton: 30 },
  { id: 205, name: "Miramar", idCanton: 31 },
  { id: 206, name: "La Unión", idCanton: 31 },
  { id: 207, name: "San Isidro", idCanton: 31 },
  { id: 208, name: "Puerto Cortés", idCanton: 32 },
  { id: 209, name: "Palmar", idCanton: 32 },
  { id: 210, name: "Sierpe", idCanton: 32 },
  { id: 211, name: "Piedras Blancas", idCanton: 32 },
  { id: 212, name: "Bahía Ballena", idCanton: 32 },
  { id: 213, name: "Bahía Drake", idCanton: 32 },
  { id: 214, name: "Quepos", idCanton: 33 },
  { id: 215, name: "Savegre", idCanton: 33 },
  { id: 216, name: "Naranjito", idCanton: 33 },
  { id: 217, name: "Golfito", idCanton: 34 },
  { id: 218, name: "Guaycará", idCanton: 34 },
  { id: 219, name: "Pavón", idCanton: 34 },
  { id: 220, name: "San Vito", idCanton: 35 },
  { id: 221, name: "Sabalito", idCanton: 35 },
  { id: 222, name: "Agua Buena", idCanton: 35 },
  { id: 223, name: "Limonsito", idCanton: 35 },
  { id: 224, name: "Pittier", idCanton: 35 },
  { id: 225, name: "Gutierréz Braun", idCanton: 35 },
  { id: 226, name: "Parrita", idCanton: 36 },
  { id: 227, name: "Corredor", idCanton: 37 },
  { id: 228, name: "La Cuesta", idCanton: 37 },
  { id: 229, name: "Canoas", idCanton: 37 },
  { id: 230, name: "Laurel", idCanton: 37 },
  { id: 231, name: "Jacó", idCanton: 38 },
  { id: 232, name: "Tárcoles", idCanton: 38 },
  { id: 233, name: "Monteverde", idCanton: 39 },
  { id: 234, name: "Puerto Jiménez", idCanton: 40 },
  { id: 235, name: "Alajuela", idCanton: 41 },
  { id: 236, name: "San José", idCanton: 41 },
  { id: 237, name: "Carrizal", idCanton: 41 },
  { id: 238, name: "San Antonio", idCanton: 41 },
  { id: 239, name: "La Guácima", idCanton: 41 },
  { id: 240, name: "San Isidro", idCanton: 41 },
  { id: 241, name: "Sabanilla", idCanton: 41 },
  { id: 242, name: "San Rafael", idCanton: 41 },
  { id: 243, name: "Río Segundo", idCanton: 41 },
  { id: 244, name: "Desamparados", idCanton: 41 },
  { id: 245, name: "Turrúcares", idCanton: 41 },
  { id: 246, name: "Tambor", idCanton: 41 },
  { id: 247, name: "La Garita", idCanton: 41 },
  { id: 248, name: "Sarapiquí", idCanton: 41 },
  { id: 249, name: "San Ramón", idCanton: 42 },
  { id: 250, name: "Santiago", idCanton: 42 },
  { id: 251, name: "San Juan", idCanton: 42 },
  { id: 252, name: "Piedades Norte", idCanton: 42 },
  { id: 253, name: "Piedades Sur", idCanton: 42 },
  { id: 254, name: "San Rafael", idCanton: 42 },
  { id: 255, name: "San Isidro", idCanton: 42 },
  { id: 256, name: "Ángeles", idCanton: 42 },
  { id: 257, name: "Alfaro", idCanton: 42 },
  { id: 258, name: "Volio", idCanton: 42 },
  { id: 259, name: "Concepción", idCanton: 42 },
  { id: 260, name: "Zapotal", idCanton: 42 },
  { id: 261, name: "Peñas Blancas", idCanton: 42 },
  { id: 262, name: "San Lorenzo", idCanton: 42 },
  { id: 263, name: "Grecia", idCanton: 43 },
  { id: 264, name: "San Isidro", idCanton: 43 },
  { id: 265, name: "San José", idCanton: 43 },
  { id: 266, name: "San Roque", idCanton: 43 },
  { id: 267, name: "Tacares", idCanton: 43 },
  { id: 268, name: "Puente de Piedra", idCanton: 43 },
  { id: 269, name: "Bolívar", idCanton: 43 },
  { id: 270, name: "San Mateo", idCanton: 44 },
  { id: 271, name: "Desmonte", idCanton: 44 },
  { id: 272, name: "Jesús María", idCanton: 44 },
  { id: 273, name: "Labrador", idCanton: 44 },
  { id: 274, name: "Atenas", idCanton: 45 },
  { id: 275, name: "Jesús", idCanton: 45 },
  { id: 276, name: "Mercedes", idCanton: 45 },
  { id: 277, name: "San Isidro", idCanton: 45 },
  { id: 278, name: "Concepción", idCanton: 45 },
  { id: 279, name: "San José", idCanton: 45 },
  { id: 280, name: "Santa Eulalia", idCanton: 45 },
  { id: 281, name: "Escobal", idCanton: 45 },
  { id: 282, name: "Naranjo", idCanton: 46 },
  { id: 283, name: "San Miguel", idCanton: 46 },
  { id: 284, name: "San José", idCanton: 46 },
  { id: 285, name: "Cirrí Sur", idCanton: 46 },
  { id: 286, name: "San Jerónimo", idCanton: 46 },
  { id: 287, name: "San Juan", idCanton: 46 },
  { id: 288, name: "El Rosario", idCanton: 46 },
  { id: 289, name: "Palmitos", idCanton: 46 },
  { id: 290, name: "Palmares", idCanton: 47 },
  { id: 291, name: "Zaragoza", idCanton: 47 },
  { id: 292, name: "Buenos Aires", idCanton: 47 },
  { id: 293, name: "Santiago", idCanton: 47 },
  { id: 294, name: "Candelaria", idCanton: 47 },
  { id: 295, name: "Esquipulas", idCanton: 47 },
  { id: 296, name: "La Granja", idCanton: 47 },
  { id: 297, name: "San Pedro", idCanton: 48 },
  { id: 298, name: "San Juan", idCanton: 48 },
  { id: 299, name: "San Rafael", idCanton: 48 },
  { id: 300, name: "Carrillos", idCanton: 48 },
  { id: 301, name: "Sabanda Redonda", idCanton: 48 },
  { id: 302, name: "Orotina", idCanton: 49 },
  { id: 303, name: "El Mastate", idCanton: 49 },
  { id: 304, name: "Hacienda Vieja", idCanton: 49 },
  { id: 305, name: "Coyolar", idCanton: 49 },
  { id: 306, name: "La Ceiba", idCanton: 49 },
  { id: 307, name: "Quesada", idCanton: 50 },
  { id: 308, name: "Florencia", idCanton: 50 },
  { id: 309, name: "Buenavista", idCanton: 50 },
  { id: 310, name: "Aguas Zarcas", idCanton: 50 },
  { id: 311, name: "Venecia", idCanton: 50 },
  { id: 312, name: "Pital", idCanton: 50 },
  { id: 313, name: "La Fortuna", idCanton: 50 },
  { id: 314, name: "La Tigra", idCanton: 50 },
  { id: 315, name: "La Palmera", idCanton: 50 },
  { id: 316, name: "Venado", idCanton: 50 },
  { id: 317, name: "Cutris", idCanton: 50 },
  { id: 318, name: "Monterrey", idCanton: 50 },
  { id: 319, name: "Pocosol", idCanton: 50 },
  { id: 320, name: "Zarcero", idCanton: 51 },
  { id: 321, name: "Laguna", idCanton: 51 },
  { id: 322, name: "Tapesco", idCanton: 51 },
  { id: 323, name: "Guadalupe", idCanton: 51 },
  { id: 324, name: "Palmira", idCanton: 51 },
  { id: 325, name: "Zapote", idCanton: 51 },
  { id: 326, name: "Brisas", idCanton: 51 },
  { id: 327, name: "Sarchí Norte", idCanton: 52 },
  { id: 328, name: "Sarchí Sur", idCanton: 52 },
  { id: 329, name: "Toro Amarillo", idCanton: 52 },
  { id: 330, name: "San Pedro", idCanton: 52 },
  { id: 331, name: "Rodríguez", idCanton: 52 },
  { id: 332, name: "Upala", idCanton: 53 },
  { id: 333, name: "Aguas Claras", idCanton: 53 },
  { id: 334, name: "San José", idCanton: 53 },
  { id: 335, name: "Bijagua", idCanton: 53 },
  { id: 336, name: "Delicias", idCanton: 53 },
  { id: 337, name: "Dos Ríos", idCanton: 53 },
  { id: 338, name: "Yolillal", idCanton: 53 },
  { id: 339, name: "Canalete", idCanton: 53 },
  { id: 340, name: "Los Chiles", idCanton: 54 },
  { id: 341, name: "Caño Negro", idCanton: 54 },
  { id: 342, name: "El Amparo", idCanton: 54 },
  { id: 343, name: "San Jorge", idCanton: 54 },
  { id: 344, name: "San Rafael", idCanton: 55 },
  { id: 345, name: "Buenavista", idCanton: 55 },
  { id: 346, name: "Cote", idCanton: 55 },
  { id: 347, name: "Katira", idCanton: 55 },
  { id: 348, name: "Río Cuarto", idCanton: 56 },
  { id: 349, name: "Santa Rita", idCanton: 56 },
  { id: 350, name: "Santa Isabel", idCanton: 56 },
  { id: 351, name: "Heredia", idCanton: 57 },
  { id: 352, name: "Mercedes", idCanton: 57 },
  { id: 353, name: "San Francisco", idCanton: 57 },
  { id: 354, name: "Ulloa", idCanton: 57 },
  { id: 355, name: "Varablanca", idCanton: 57 },
  { id: 356, name: "Barva", idCanton: 58 },
  { id: 357, name: "San José de la Montaña", idCanton: 58 },
  { id: 358, name: "San Pablo", idCanton: 58 },
  { id: 359, name: "San Pedro", idCanton: 58 },
  { id: 360, name: "San Roque", idCanton: 58 },
  { id: 361, name: "Santa Lucía", idCanton: 58 },
  { id: 362, name: "La asunción", idCanton: 59 },
  { id: 363, name: "La Ribera", idCanton: 59 },
  { id: 364, name: "San Antonio", idCanton: 59 },
  { id: 365, name: "Barrantes", idCanton: 60 },
  { id: 366, name: "Llorente", idCanton: 60 },
  { id: 367, name: "San Joaquín", idCanton: 60 },
  { id: 368, name: "Concepción", idCanton: 61 },
  { id: 369, name: "San Francisco", idCanton: 61 },
  { id: 370, name: "San Isidro", idCanton: 61 },
  { id: 371, name: "San José", idCanton: 61 },
  { id: 372, name: "Rincón de Sabanilla", idCanton: 62 },
  { id: 373, name: "San Pablo", idCanton: 62 },
  { id: 374, name: "Ángeles", idCanton: 63 },
  { id: 387, name: "San Miguel", idCanton: 65 },
  { id: 388, name: "San Vicente", idCanton: 65 },
  { id: 389, name: "Santa Rosa", idCanton: 65 },
  { id: 390, name: "Santo Domingo", idCanton: 65 },
  { id: 391, name: "Santo Tomás", idCanton: 65 },
  { id: 392, name: "Tures", idCanton: 65 },
  { id: 393, name: "Cureña", idCanton: 66 },
  { id: 394, name: "La Virgen", idCanton: 66 },
  { id: 395, name: "Las Horquetas", idCanton: 66 },
  { id: 396, name: "Llanuras del Gaspar", idCanton: 66 },
  { id: 397, name: "Puerto Viejo", idCanton: 66 },
  { id: 398, name: "Liberia", idCanton: 67 },
  { id: 399, name: "Cañas Dulces", idCanton: 67 },
  { id: 400, name: "Mayorga", idCanton: 67 },
  { id: 401, name: "Nacascolo", idCanton: 67 },
  { id: 402, name: "Curubandé", idCanton: 67 },
  { id: 403, name: "Nicoya", idCanton: 68 },
  { id: 404, name: "Mansión", idCanton: 68 },
  { id: 405, name: "San Antonio", idCanton: 68 },
  { id: 406, name: "Quebrada Honda", idCanton: 68 },
  { id: 407, name: "Sámara", idCanton: 68 },
  { id: 408, name: "Nosara", idCanton: 68 },
  { id: 409, name: "Belén de Nosarita", idCanton: 68 },
  { id: 410, name: "Santa Cruz", idCanton: 69 },
  { id: 411, name: "Bolsón", idCanton: 69 },
  { id: 412, name: "Veintisiete de Abril", idCanton: 69 },
  { id: 413, name: "Tempate", idCanton: 69 },
  { id: 414, name: "Cartagena", idCanton: 69 },
  { id: 415, name: "Cuajiniquil", idCanton: 69 },
  { id: 416, name: "Diriá", idCanton: 69 },
  { id: 417, name: "Cabos Velas", idCanton: 69 },
  { id: 418, name: "Tamarindo", idCanton: 69 },
  { id: 419, name: "Bagaces", idCanton: 70 },
  { id: 420, name: "La Fortuna", idCanton: 70 },
  { id: 421, name: "Mogote", idCanton: 70 },
  { id: 422, name: "Río Naranjo", idCanton: 70 },
  { id: 423, name: "Filadelfia", idCanton: 71 },
  { id: 424, name: "Palmira", idCanton: 71 },
  { id: 425, name: "Sardinal", idCanton: 71 },
  { id: 426, name: "Belén", idCanton: 71 },
  { id: 427, name: "Cañas", idCanton: 72 },
  { id: 428, name: "Palmira", idCanton: 72 },
  { id: 429, name: "San Miguel", idCanton: 72 },
  { id: 430, name: "Bebedero", idCanton: 72 },
  { id: 431, name: "Porozal", idCanton: 72 },
  { id: 432, name: "Las Juntas", idCanton: 73 },
  { id: 433, name: "Sierra", idCanton: 73 },
  { id: 434, name: "San Juan", idCanton: 73 },
  { id: 435, name: "Colorado", idCanton: 73 },
  { id: 436, name: "Tilarán", idCanton: 74 },
  { id: 437, name: "Quebrada Grande", idCanton: 74 },
  { id: 438, name: "Tronadora", idCanton: 74 },
  { id: 439, name: "Santa Rosa", idCanton: 74 },
  { id: 440, name: "Líbano", idCanton: 74 },
  { id: 441, name: "Tierras Morenas", idCanton: 74 },
  { id: 442, name: "Arenal", idCanton: 74 },
  { id: 443, name: "Cabeceras", idCanton: 74 },
  { id: 444, name: "Carmona", idCanton: 75 },
  { id: 445, name: "Santa Rita", idCanton: 75 },
  { id: 446, name: "Zapotal", idCanton: 75 },
  { id: 447, name: "San Pablo", idCanton: 75 },
  { id: 448, name: "Porvenir", idCanton: 75 },
  { id: 449, name: "Bejuco", idCanton: 75 },
  { id: 450, name: "La Cruz", idCanton: 76 },
  { id: 451, name: "Santa Cecilia", idCanton: 76 },
  { id: 452, name: "La Garita", idCanton: 76 },
  { id: 453, name: "Santa Elena", idCanton: 76 },
  { id: 454, name: "Hojancha", idCanton: 77 },
  { id: 455, name: "Monte Romo", idCanton: 77 },
  { id: 456, name: "Puerto Carrillo", idCanton: 77 },
  { id: 457, name: "Huacas", idCanton: 77 },
  { id: 458, name: "Matambú", idCanton: 77 },
  { id: 459, name: "Limón", idCanton: 78 },
  { id: 460, name: "Valle La Estrella", idCanton: 78 },
  { id: 461, name: "Río Blanco", idCanton: 78 },
  { id: 462, name: "Matama", idCanton: 78 },
  { id: 463, name: "Guápiles", idCanton: 79 },
  { id: 464, name: "Jiménez", idCanton: 79 },
  { id: 465, name: "La Rita", idCanton: 79 },
  { id: 466, name: "Roxana", idCanton: 79 },
  { id: 467, name: "Cariari", idCanton: 79 },
  { id: 468, name: "Colorado", idCanton: 79 },
  { id: 469, name: "La Corona", idCanton: 79 },
  { id: 470, name: "Siquirres", idCanton: 80 },
  { id: 471, name: "Pacuarito", idCanton: 80 },
  { id: 472, name: "Florida", idCanton: 80 },
  { id: 473, name: "Germania", idCanton: 80 },
  { id: 474, name: "Cairo", idCanton: 80 },
  { id: 475, name: "Alegría", idCanton: 80 },
  { id: 476, name: "Reventazón", idCanton: 80 },
  { id: 477, name: "Bratsi", idCanton: 81 },
  { id: 478, name: "Sixaola", idCanton: 81 },
  { id: 479, name: "Cahuita", idCanton: 81 },
  { id: 480, name: "Telire", idCanton: 81 },
  { id: 481, name: "Matina", idCanton: 82 },
  { id: 482, name: "Batán", idCanton: 82 },
  { id: 483, name: "Carrandi", idCanton: 82 },
  { id: 484, name: "Guácimo", idCanton: 83 },
  { id: 485, name: "Mercedes", idCanton: 83 },
  { id: 486, name: "Pocora", idCanton: 83 },
  { id: 487, name: "Río Jiménez", idCanton: 83 },
  { id: 488, name: "Duacarí", idCanton: 83 },
  { id: 492, name: "X1", idCanton: 20 },
  { id: 375, name: "Concepción", idCanton: 63 },
  { id: 376, name: "San Josecito", idCanton: 63 },
  { id: 377, name: "San Rafael", idCanton: 63 },
  { id: 378, name: "Santiago", idCanton: 63 },
  { id: 379, name: "Jesús", idCanton: 64 },
  { id: 380, name: "Purabá", idCanton: 64 },
  { id: 381, name: "San Juan", idCanton: 64 },
  { id: 382, name: "San Pedro", idCanton: 64 },
  { id: 383, name: "Santa Bárbara", idCanton: 64 },
  { id: 384, name: "Santo Domingo", idCanton: 64 },
  { id: 385, name: "Pará", idCanton: 65 },
  { id: 386, name: "Paracito", idCanton: 65 },
];

export function getCantons(provinceId) {
  const result = [];
  const id = parseInt(provinceId, 10);
  for (let i = 0; i < cantons.length; i++) {
    if (cantons[i].idProvince === id) {
      result.push(cantons[i]);
    }
  }
  return result;
}

export function getDistricts(cantonId) {
  const result = [];
  const id = parseInt(cantonId, 10);
  for (let i = 0; i < districts.length; i++) {
    if (districts[i].idCanton === id) {
      result.push(districts[i]);
    }
  }
  return result;
}
